"""Canonicalize skill names for vacancy and resume evidence."""
from __future__ import annotations


SKILL_ALIASES = {
    "fast api": "fastapi",
    "переговоров": "negotiation",
    "переговорах": "negotiation",
    "управление проектами": "project management",
    "управления проектами": "project management",
    "управлял проектами": "project management",
    "управляла проектами": "project management",
    "управление продуктом": "product management",
    "управления продуктом": "product management",
    "сбором требований": "requirements gathering",
    "анализом требований": "requirements analysis",
    "пользовательских историй": "user stories",
    "дорожной карты": "roadmap",
    "кастдевов": "customer development",
    "продуктовой аналитикой": "product analytics",
    "менторство": "mentoring",
    "управление временем": "time management",
    "team player": "teamwork",
    "готовность учиться": "fast learning",
    "внимательность": "attention to detail",
    "питон": "python",
    "питоне": "python",
    "питоном": "python",
    "postres": "postgresql",
    "постгрес": "postgresql",
    "постгресом": "postgresql",
    "докер": "docker",
    "гит": "git",
    ".net": "dotnet",
    ".net core": "dotnet",
    "net core": "dotnet",
    "asp.net": "dotnet",
    "ms sql": "mssql",
    "microsoft sql server": "mssql",
    "sql server": "mssql",
    "postgres": "postgresql",
    "postgre": "postgresql",
    "js": "javascript",
    "ts": "typescript",
    "react.js": "react",
    "reactjs": "react",
    "vue.js": "vue",
    "vuejs": "vue",
    "vue js": "vue",
    "nodejs": "node.js",
    "node": "node.js",
    "golang": "go",
    "c sharp": "c#",
    "spring boot": "spring",
    "sql alchemy": "sqlalchemy",
    "entity framework core": "entity framework",
    "ef core": "entity framework",
    "rabbit mq": "rabbitmq",
    "apache kafka": "kafka",
    "k8s": "kubernetes",
    "gitlab-ci": "gitlab ci",
    "cicd": "ci/cd",
    "continuous integration": "ci/cd",
    "continuous delivery": "ci/cd",
    "unit tests": "unit testing",
    "unit test": "unit testing",
    "юнит тесты": "unit testing",
    "юнит-тесты": "unit testing",
    "модульные тесты": "unit testing",
    "codereview": "code review",
    "code review": "code review",
    "ревью кода": "code review",
    "сырой sql": "raw sql",
    "сырые sql запросы": "raw sql",
    "сырые запросы": "raw sql",
    "sql profiling": "sql profiling",
    "профилирование sql": "sql profiling",
    "тест кейсы": "test cases",
    "тест-кейсы": "test cases",
    "тестовая документация": "test documentation",
    "баг-репорты": "bug reporting",
    "ручное тестирование": "manual testing",
    "автотесты": "automated testing",
    "автоматизированное тестирование": "automated testing",
    "test automation": "automated testing",
    "сбор требований": "requirements gathering",
    "выявление требований": "requirements gathering",
    "анализ требований": "requirements analysis",
    "пользовательские истории": "user stories",
    "user story": "user stories",
    "управление backlog": "backlog management",
    "управление бэклогом": "backlog management",
    "бэклог": "backlog management",
    "дорожная карта": "roadmap",
    "роадмап": "roadmap",
    "custdev": "customer development",
    "кастдев": "customer development",
    "продуктовая аналитика": "product analytics",
    "ab testing": "a/b testing",
    "a/b тестирование": "a/b testing",
    "ab тестирование": "a/b testing",
    "спецификация api": "api specification",
    "описание api": "api specification",
    "техническое задание": "technical specification",
    "тз": "technical specification",
    "моделирование бизнес-процессов": "business process modeling",
    "business process modelling": "business process modeling",
    "product manager": "product management",
    "продакт": "product management",
    "product owner": "product management",
    "project manager": "project management",
    "проектный менеджмент": "project management",
    "менеджер проектов": "project management",
    "аналитика": "analytics",
    "user experience": "ux",
    "user interface": "ui",
    "яндекс.директ": "yandex direct",
    "яндекс директ": "yandex direct",
    "click house": "clickhouse",
    "elastic search": "elasticsearch",
    "yandex cloud": "yandex cloud",
    "яндекс cloud": "yandex cloud",
    "коммуникация": "communication",
    "коммуникабельность": "communication",
    "общение": "communication",
    "communication": "communication",
    "командная работа": "teamwork",
    "работа в команде": "teamwork",
    "teamwork": "teamwork",
    "ответственность": "responsibility",
    "responsibility": "responsibility",
    "быстрая обучаемость": "fast learning",
    "обучаемость": "fast learning",
    "fast learning": "fast learning",
    "самоорганизация": "self organization",
    "self organization": "self organization",
    "self-organization": "self organization",
    "решение проблем": "problem solving",
    "умение решать проблемы": "problem solving",
    "находить решение к проблемам": "problem solving",
    "находить решение проблем": "problem solving",
    "находить решения проблем": "problem solving",
    "способность находить решение к проблемам": "problem solving",
    "problem solving": "problem solving",
    "внимательность к деталям": "attention to detail",
    "attention to detail": "attention to detail",
    "адаптивность": "adaptability",
    "adaptability": "adaptability",
    "лидерство": "leadership",
    "leadership": "leadership",
    "наставничество": "mentoring",
    "mentoring": "mentoring",
    "тайм-менеджмент": "time management",
    "time management": "time management",
    "работа со стейкхолдерами": "stakeholder communication",
    "взаимодействие со стейкхолдерами": "stakeholder communication",
    "stakeholder communication": "stakeholder communication",
    "деловая коммуникация": "business communication",
    "деловое общение": "business communication",
    "business communication": "business communication",
    "business communications": "business communication",
    "презентации": "presentation skills",
    "делать презентации": "presentation skills",
    "подготовка презентаций": "presentation skills",
    "проводить презентации": "presentation skills",
    "presentation skills": "presentation skills",
    "presentations": "presentation skills",
    "переговоры": "negotiation",
    "ведение переговоров": "negotiation",
    "negotiation": "negotiation",
    "negotiations": "negotiation",
    "управление стейкхолдерами": "stakeholder management",
    "stakeholder management": "stakeholder management",
    "клиентоориентированность": "client orientation",
    "клиент ориентированность": "client orientation",
    "customer focus": "client orientation",
    "client orientation": "client orientation",
    "грамотная речь": "clear speech",
    "clear speech": "clear speech",
    "умение искать и находить необходимую информацию": "information search",
    "поиск информации": "information search",
    "information search": "information search",
    "работа с большим объемом информации": "large information volume",
    "работа с большим объёмом информации": "large information volume",
    "large information volume": "large information volume",
    "интерес к it-сфере": "interest in it",
    "интерес к it": "interest in it",
    "interest in it": "interest in it",
    "желание развиваться и обучаться": "growth mindset",
    "желание развиваться": "growth mindset",
    "growth mindset": "growth mindset",
    "способность осваивать новые технологии": "fast learning",
    "осваивать новые технологии": "fast learning",
    "холодные продажи": "cold sales",
    "холодные звонки": "cold calls",
    "навыки продаж": "sales skills",
    "работа с возражениями": "objection handling",
    "опыт в b2b": "b2b experience",
    "опыт в it": "it experience",
    "опыт в консалтинге": "consulting experience",
    "работа с crm": "crm",
}

def normalize_skill(value: str) -> str:
    skill = value.strip().lower().replace("ё", "е")
    skill = SKILL_ALIASES.get(skill, skill)
    return skill
